apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  url: cG9zdGdyZXNxbDovL293bmVyOjk1dkdzTHlIRWxhV0BlcC1kYXduLWJhbmQtYTY3N3F6ZmoudXMtd2VzdC0yLmF3cy5uZW9uLnRlY2gvcGFzc2luP3NzbG1vZGU9cmVxdWlyZQo=
